<?php
# PackageStates.php

# This file is maintained by TYPO3's package management. Although you can edit it
# manually, you should rather use the extension manager for maintaining packages.
# This file will be regenerated automatically if it doesn't exist. Deleting this file
# should, however, never become necessary if you use the package commands.

return [
    'packages' => [
        'core' => [
            'composerName' => 'typo3/cms-core',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/core/',
            'suggestions' => [],
        ],
        'extbase' => [
            'composerName' => 'typo3/cms-extbase',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/extbase/',
            'suggestions' => [],
        ],
        'fluid' => [
            'composerName' => 'typo3/cms-fluid',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/fluid/',
            'suggestions' => [],
        ],
        'extensionmanager' => [
            'composerName' => 'typo3/cms-extensionmanager',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/extensionmanager/',
            'suggestions' => [],
        ],
        'lang' => [
            'composerName' => 'typo3/cms-lang',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/lang/',
            'suggestions' => [],
        ],
        'setup' => [
            'composerName' => 'typo3/cms-setup',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/setup/',
            'suggestions' => [],
        ],
        'rtehtmlarea' => [
            'composerName' => 'typo3/cms-rtehtmlarea',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/rtehtmlarea/',
            'suggestions' => [
                'setup',
            ],
        ],
        'rsaauth' => [
            'composerName' => 'typo3/cms-rsaauth',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/rsaauth/',
            'suggestions' => [],
        ],
        'saltedpasswords' => [
            'composerName' => 'typo3/cms-saltedpasswords',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/saltedpasswords/',
            'suggestions' => [
                'rsaauth',
            ],
        ],
        'backend' => [
            'composerName' => 'typo3/cms-backend',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/backend/',
            'suggestions' => [],
        ],
        'belog' => [
            'composerName' => 'typo3/cms-belog',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/belog/',
            'suggestions' => [],
        ],
        'filelist' => [
            'composerName' => 'typo3/cms-filelist',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/filelist/',
            'suggestions' => [],
        ],
        'fluid_styled_content' => [
            'composerName' => 'typo3/cms-fluid-styled-content',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/fluid_styled_content/',
            'suggestions' => [],
        ],
        'form' => [
            'composerName' => 'typo3/cms-form',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/form/',
            'suggestions' => [],
        ],
        'frontend' => [
            'composerName' => 'typo3/cms-frontend',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/frontend/',
            'suggestions' => [],
        ],
        'func' => [
            'composerName' => 'typo3/cms-func',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/func/',
            'suggestions' => [],
        ],
        'info' => [
            'composerName' => 'typo3/cms-info',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/info/',
            'suggestions' => [],
        ],
        'install' => [
            'composerName' => 'typo3/cms-install',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/install/',
            'suggestions' => [],
        ],
        'lowlevel' => [
            'composerName' => 'typo3/cms-lowlevel',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/lowlevel/',
            'suggestions' => [],
        ],
        'recordlist' => [
            'composerName' => 'typo3/cms-recordlist',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/recordlist/',
            'suggestions' => [],
        ],
        'reports' => [
            'composerName' => 'typo3/cms-reports',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/reports/',
            'suggestions' => [],
        ],
        'sv' => [
            'composerName' => 'typo3/cms-sv',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/sv/',
            'suggestions' => [],
        ],
        't3skin' => [
            'composerName' => 'typo3/cms-t3skin',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/t3skin/',
            'suggestions' => [],
        ],
        'tstemplate' => [
            'composerName' => 'typo3/cms-tstemplate',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/tstemplate/',
            'suggestions' => [],
        ],
        'realurl' => [
            'composerName' => 'helhum/realurl',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/realurl/',
            'suggestions' => [
                'static_info_tables',
            ],
        ],
        't3theme_typo3com' => [
            'composerName' => 't3com/t3theme-typo3com',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/t3theme_typo3com/',
            'suggestions' => [],
        ],
        'about' => [
            'composerName' => 'typo3/cms-about',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/about/',
            'suggestions' => [],
        ],
        'aboutmodules' => [
            'composerName' => 'typo3/cms-aboutmodules',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/aboutmodules/',
            'suggestions' => [],
        ],
        'adodb' => [
            'composerName' => 'typo3/cms-adodb',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/adodb/',
            'suggestions' => [],
        ],
        'amqp' => [
            'composerName' => 'amqp',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/amqp/',
            'suggestions' => [],
        ],
        'beuser' => [
            'composerName' => 'typo3/cms-beuser',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/beuser/',
            'suggestions' => [],
        ],
        'bootstrap_grids' => [
            'composerName' => 'laxap/bootstrap-grids',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/bootstrap_grids/',
            'suggestions' => [],
        ],
        'context_help' => [
            'composerName' => 'typo3/cms-context-help',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/context_help/',
            'suggestions' => [],
        ],
        'cshmanual' => [
            'composerName' => 'typo3/cms-cshmanual',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/cshmanual/',
            'suggestions' => [],
        ],
        'css_styled_content' => [
            'composerName' => 'typo3/cms-css-styled-content',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/css_styled_content/',
            'suggestions' => [],
        ],
        'cz_simple_cal' => [
            'composerName' => 'cz_simple_cal',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/cz_simple_cal/',
            'suggestions' => [
                'scheduler',
            ],
        ],
        'dbal' => [
            'composerName' => 'typo3/cms-dbal',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/dbal/',
            'suggestions' => [],
        ],
        'documentation' => [
            'composerName' => 'typo3/cms-documentation',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/documentation/',
            'suggestions' => [],
        ],
        'feedit' => [
            'composerName' => 'typo3/cms-feedit',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/feedit/',
            'suggestions' => [],
        ],
        'felogin' => [
            'composerName' => 'typo3/cms-felogin',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/felogin/',
            'suggestions' => [],
        ],
        'filemetadata' => [
            'composerName' => 'typo3/cms-filemetadata',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/filemetadata/',
            'suggestions' => [],
        ],
        'gridelements' => [
            'composerName' => 'GridElementsTeam/Gridelements',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/gridelements/',
            'suggestions' => [],
        ],
        'impexp' => [
            'composerName' => 'typo3/cms-impexp',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/impexp/',
            'suggestions' => [],
        ],
        'indexed_search' => [
            'composerName' => 'typo3/cms-indexed-search',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/indexed_search/',
            'suggestions' => [],
        ],
        'indexed_search_mysql' => [
            'composerName' => 'typo3/cms-indexed-search-mysql',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/indexed_search_mysql/',
            'suggestions' => [],
        ],
        'info_pagetsconfig' => [
            'composerName' => 'typo3/cms-info-pagetsconfig',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/info_pagetsconfig/',
            'suggestions' => [],
        ],
        'linkvalidator' => [
            'composerName' => 'typo3/cms-linkvalidator',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/linkvalidator/',
            'suggestions' => [],
        ],
        'news' => [
            'composerName' => 'georgringer/news',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/news/',
            'suggestions' => [],
        ],
        'opendocs' => [
            'composerName' => 'typo3/cms-opendocs',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/opendocs/',
            'suggestions' => [],
        ],
        'owl_slider' => [
            'composerName' => 'owl_slider',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/owl_slider/',
            'suggestions' => [],
        ],
        'randombanners' => [
            'composerName' => 'randombanners',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/randombanners/',
            'suggestions' => [],
        ],
        'recycler' => [
            'composerName' => 'typo3/cms-recycler',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/recycler/',
            'suggestions' => [],
        ],
        'scheduler' => [
            'composerName' => 'typo3/cms-scheduler',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/scheduler/',
            'suggestions' => [],
        ],
        'solr' => [
            'composerName' => 'apache-solr-for-typo3/solr',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/solr/',
            'suggestions' => [],
        ],
        'solr_redmine' => [
            'composerName' => 'solr_redmine',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/solr_redmine/',
            'suggestions' => [],
        ],
        'static_info_tables' => [
            'composerName' => 'sjbr/static-info-tables',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/static_info_tables/',
            'suggestions' => [],
        ],
        'sys_action' => [
            'composerName' => 'typo3/cms-sys-action',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/sys_action/',
            'suggestions' => [],
        ],
        'sys_note' => [
            'composerName' => 'typo3/cms-sys-note',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/sys_note/',
            'suggestions' => [],
        ],
        't3editor' => [
            'composerName' => 'typo3/cms-t3editor',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/t3editor/',
            'suggestions' => [],
        ],
        't3org_flickrfeed' => [
            'composerName' => 't3org_flickrfeed',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/t3org_flickrfeed/',
            'suggestions' => [],
        ],
        't3org_spamremover' => [
            'composerName' => 't3org_spamremover',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/t3org_spamremover/',
            'suggestions' => [],
        ],
        't3theme' => [
            'composerName' => 'typo3/t3theme',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/t3theme/',
            'suggestions' => [
                'static_info_tables',
                'gridelements',
                'css_styled_content',
            ],
        ],
        'taskcenter' => [
            'composerName' => 'typo3/cms-taskcenter',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/taskcenter/',
            'suggestions' => [
                'sys_action',
            ],
        ],
        'typo3_console' => [
            'composerName' => 'helhum/typo3-console',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/typo3_console/',
            'suggestions' => [],
        ],
        'version' => [
            'composerName' => 'typo3/cms-version',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/version/',
            'suggestions' => [],
        ],
        'viewpage' => [
            'composerName' => 'typo3/cms-viewpage',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/viewpage/',
            'suggestions' => [],
        ],
        'voice' => [
            'composerName' => 'voice',
            'state' => 'inactive',
            'packagePath' => 'typo3conf/ext/voice/',
            'suggestions' => [],
        ],
        'wizard_crpages' => [
            'composerName' => 'typo3/cms-wizard-crpages',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/wizard_crpages/',
            'suggestions' => [],
        ],
        'wizard_sortpages' => [
            'composerName' => 'typo3/cms-wizard-sortpages',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/wizard_sortpages/',
            'suggestions' => [],
        ],
        'workspaces' => [
            'composerName' => 'typo3/cms-workspaces',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/workspaces/',
            'suggestions' => [],
        ],
    ],
    'version' => 4,
];
