<?php

########################################################################
# Extension Manager/Repository config file for ext: "randombanners"
#
# Auto generated by Extbase Kickstarter 2011-04-18
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Random banner display',
	'description' => 'Random banner with display and click statistics',
	'category' => 'plugin',
	'author' => 'Thomas Loeffler',
	'author_email' => 'loeffler@spooner-web.de',
	'author_company' => '',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid,extbase_dam',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>