<?php

########################################################################
# Extension Manager/Repository config file for ext: "t3org_spamremover"
#
# Auto generated by Extension Builder 2014-03-07
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Spam Remover for typo3org',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Christian Zenker',
	'author_email' => 'typo3@xopn.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
			'amqp' => '*',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>